## Import

In [2]:
from torch import nn,optim
import torch
from torch.utils.data import DataLoader,Dataset,TensorDataset
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

## Data

In [3]:
df = pd.read_csv('./diabetes.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
no_zero = ['Glucose','BloodPressure','SkinThickness','Insulin','BMI']

for feature in no_zero:
     df[feature] = df[feature].replace(0,np.nan)
     mean = df[feature].mean()
     df[feature] = df[feature].replace(np.nan,mean)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.00000,155.548223,33.6,0.627,50,1
1,1,85.0,66.0,29.00000,155.548223,26.6,0.351,31,0
2,8,183.0,64.0,29.15342,155.548223,23.3,0.672,32,1
3,1,89.0,66.0,23.00000,94.000000,28.1,0.167,21,0
4,0,137.0,40.0,35.00000,168.000000,43.1,2.288,33,1

In [5]:
X = df.drop('Outcome',axis=1)
X.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148.0,72.0,35.00000,155.548223,33.6,0.627,50
1,1,85.0,66.0,29.00000,155.548223,26.6,0.351,31
2,8,183.0,64.0,29.15342,155.548223,23.3,0.672,32
3,1,89.0,66.0,23.00000,94.000000,28.1,0.167,21
4,0,137.0,40.0,35.00000,168.000000,43.1,2.288,33

In [19]:
y = np.array(df['Outcome'])
y[:5]

array([1, 0, 1, 0, 1])

In [20]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=12,stratify=y)
X_train , X_valid , y_train , y_valid = train_test_split(X_train,y_train,test_size=0.09,random_state=12,stratify=y_train)

X_train.shape , X_valid.shape , X_test.shape , y_train.shape ,y_valid.shape , y_test.shape

((558, 8), (56, 8), (154, 8), (558,), (56,), (154,))

In [21]:
X_scaler = StandardScaler()

X_train = X_scaler.fit_transform(X_train)
X_valid = X_scaler.transform(X_valid)
X_test = X_scaler.transform(X_test)

X_train.shape , X_valid.shape , X_test.shape , y_train.shape ,y_valid.shape , y_test.shape

((558, 8), (56, 8), (154, 8), (558,), (56,), (154,))

In [22]:
X_train = torch.tensor(X_train, dtype=torch.float32)
X_valid = torch.tensor(X_valid, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)

y_train = torch.tensor(y_train, dtype=torch.float32)
y_valid = torch.tensor(y_valid, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32)

X_train.shape , X_valid.shape , X_test.shape , y_train.shape ,y_valid.shape , y_test.shape

(torch.Size([558, 8]),
 torch.Size([56, 8]),
 torch.Size([154, 8]),
 torch.Size([558]),
 torch.Size([56]),
 torch.Size([154]))

In [23]:
train_set = TensorDataset(X_train,y_train)
valid_set = TensorDataset(X_valid,y_valid)
test_set = TensorDataset(X_test,y_test)

In [24]:
train_loader = DataLoader(train_set,batch_size=100,shuffle=True)
valid_loader = DataLoader(valid_set,batch_size=10,shuffle=True)
test_loader = DataLoader(test_set,batch_size=200,shuffle=True)

## Model and Training and Validation

In [62]:
class LogisticRegression(nn.Module):
    def __init__(self,in_features) -> None:
        super(LogisticRegression,self).__init__()
        self.linear = nn.Linear(in_features,1)
    def forward(self,X):
        return torch.sigmoid(self.linear(X))

model = LogisticRegression(X_train[0].shape[0])

In [63]:
optimizer = optim.SGD(model.parameters(),lr=0.2,momentum=0.9)
get_error = nn.BCELoss()

In [ ]:
train_hist_loss = []
train_hist_acc = []
valid_hist_loss = []
valid_hist_acc = []
n_epoches = 200
best_error = torch.inf

for i in range(n_epoches):

    mean_train_loss = 0
    mean_train_acc = 0
    mean_valid_loss = 0
    mean_valid_acc = 0

    for X_batch, y_batch in train_loader:
        y_hat = model(X_batch).squeeze()
        loss = get_error(y_hat , y_batch)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if loss < best_error:
            torch.save(model, './LogisticRegressionModel.pt')

        mean_train_loss += loss.item()
        mean_train_acc += torch.sum((y_hat > 0.5).float() == y_batch).item()

    mean_train_loss = mean_train_loss / len(train_loader)
    mean_train_acc = mean_train_acc / len(train_set)

    with torch.no_grad():
        for X_batch, y_batch in valid_loader:
            y_hat = model(X_batch).squeeze()
            loss = get_error(y_hat , y_batch)

            mean_valid_loss += loss.item()
            mean_valid_acc += torch.sum((y_hat > 0.5).float() == y_batch).item()

    mean_valid_loss = mean_valid_loss / len(valid_loader)
    mean_valid_acc = mean_valid_acc / len(valid_set)

    train_hist_loss.append(mean_train_loss)
    train_hist_acc.append(mean_train_acc)
    valid_hist_loss.append(mean_valid_loss)
    valid_hist_acc.append(mean_valid_acc)

    print(f"Epoch [{i+1:3d}/{n_epoches}]\t"
          f"Train Loss: {mean_train_loss}\t"
          f"Train Acc: {mean_train_acc}\t"
          f"Valid Loss: {mean_valid_loss}\t"
          f"Valid Acc: {mean_valid_acc:}\t"    )

Epoch [  1/200]	Train Loss: 0.4698077191909154	Train Acc: 0.7759856630824373	Valid Loss: 0.4586931864420573	Valid Acc: 0.7678571428571429
Epoch [  2/200]	Train Loss: 0.4698358823855718	Train Acc: 0.7688172043010753	Valid Loss: 0.4705205609401067	Valid Acc: 0.7678571428571429
Epoch [  3/200]	Train Loss: 0.4673782289028168	Train Acc: 0.7777777777777778	Valid Loss: 0.4498865182201068	Valid Acc: 0.7678571428571429
Epoch [  4/200]	Train Loss: 0.47235750158627826	Train Acc: 0.7759856630824373	Valid Loss: 0.4663800075650215	Valid Acc: 0.7678571428571429
Epoch [  5/200]	Train Loss: 0.4733882298072179	Train Acc: 0.7688172043010753	Valid Loss: 0.48021020988623303	Valid Acc: 0.7678571428571429
Epoch [  6/200]	Train Loss: 0.46825064222017926	Train Acc: 0.7724014336917563	Valid Loss: 0.47061507403850555	Valid Acc: 0.75
Epoch [  7/200]	Train Loss: 0.47680220007896423	Train Acc: 0.7741935483870968	Valid Loss: 0.4719797770182292	Valid Acc: 0.7321428571428571
Epoch [  8/200]	Train Loss: 0.46580419937769574	Train Acc: 0.7741935483870968	Valid Loss: 0.4515180438756943	Valid Acc: 0.7678571428571429
Epoch [  9/200]	Train Loss: 0.4671487659215927	Train Acc: 0.7741935483870968	Valid Loss: 0.4844265754024188	Valid Acc: 0.7678571428571429
Epoch [ 10/200]	Train Loss: 0.4691257029771805	Train Acc: 0.7706093189964157	Valid Loss: 0.4560001442829768	Valid Acc: 0.7678571428571429
Epoch [ 11/200]	Train Loss: 0.474787175655365	Train Acc: 0.7759856630824373	Valid Loss: 0.46478407084941864	Valid Acc: 0.7678571428571429
Epoch [ 12/200]	Train Loss: 0.47534248729546863	Train Acc: 0.7759856630824373	Valid Loss: 0.47240064044793445	Valid Acc: 0.75
Epoch [ 13/200]	Train Loss: 0.46581049760182697	Train Acc: 0.7706093189964157	Valid Loss: 0.4606488148371379	Valid Acc: 0.7678571428571429
Epoch [ 14/200]	Train Loss: 0.4722241560618083	Train Acc: 0.7634408602150538	Valid Loss: 0.4517424801985423	Valid Acc: 0.7678571428571429
Epoch [ 15/200]	Train Loss: 0.47167037427425385	Train Acc: 0.7688172043010753	Valid Loss: 0.45859023928642273	Valid Acc: 0.7678571428571429
Epoch [ 16/200]	Train Loss: 0.4692768802245458	Train Acc: 0.7724014336917563	Valid Loss: 0.4675302455822627	Valid Acc: 0.7321428571428571
Epoch [ 17/200]	Train Loss: 0.46822814146677655	Train Acc: 0.7759856630824373	Valid Loss: 0.47823946674664813	Valid Acc: 0.7321428571428571
Epoch [ 18/200]	Train Loss: 0.47234058380126953	Train Acc: 0.7777777777777778	Valid Loss: 0.4672743131717046	Valid Acc: 0.7678571428571429
Epoch [ 19/200]	Train Loss: 0.46924616396427155	Train Acc: 0.7688172043010753	Valid Loss: 0.4668545921643575	Valid Acc: 0.7321428571428571
Epoch [ 20/200]	Train Loss: 0.4744168370962143	Train Acc: 0.7688172043010753	Valid Loss: 0.45203255613644916	Valid Acc: 0.75
Epoch [ 21/200]	Train Loss: 0.47054319580396015	Train Acc: 0.7670250896057348	Valid Loss: 0.4447682425379753	Valid Acc: 0.7678571428571429
Epoch [ 22/200]	Train Loss: 0.4711500555276871	Train Acc: 0.7741935483870968	Valid Loss: 0.46556391815344494	Valid Acc: 0.75
Epoch [ 23/200]	Train Loss: 0.4760729819536209	Train Acc: 0.7580645161290323	Valid Loss: 0.4563474307457606	Valid Acc: 0.7678571428571429
Epoch [ 24/200]	Train Loss: 0.4700637261072795	Train Acc: 0.7688172043010753	Valid Loss: 0.4616137047608693	Valid Acc: 0.7678571428571429
Epoch [ 25/200]	Train Loss: 0.47262708842754364	Train Acc: 0.7741935483870968	Valid Loss: 0.49711770315965015	Valid Acc: 0.7678571428571429
Epoch [ 26/200]	Train Loss: 0.4687037020921707	Train Acc: 0.7688172043010753	Valid Loss: 0.4643205503622691	Valid Acc: 0.7678571428571429
Epoch [ 27/200]	Train Loss: 0.4765462080637614	Train Acc: 0.7724014336917563	Valid Loss: 0.45358870923519135	Valid Acc: 0.7678571428571429
Epoch [ 28/200]	Train Loss: 0.4765288184086482	Train Acc: 0.7652329749103942	Valid Loss: 0.4561336189508438	Valid Acc: 0.7321428571428571
Epoch [ 29/200]	Train Loss: 0.47804058094819385	Train Acc: 0.7688172043010753	Valid Loss: 0.4439813842376073	Valid Acc: 0.7678571428571429
Epoch [ 30/200]	Train Loss: 0.48144160707791644	Train Acc: 0.7706093189964157	Valid Loss: 0.45488786200682324	Valid Acc: 0.7678571428571429
Epoch [ 31/200]	Train Loss: 0.46936339139938354	Train Acc: 0.7652329749103942	Valid Loss: 0.49213890731334686	Valid Acc: 0.7857142857142857
Epoch [ 32/200]	Train Loss: 0.4688825358947118	Train Acc: 0.7706093189964157	Valid Loss: 0.49078144629796344	Valid Acc: 0.75
Epoch [ 33/200]	Train Loss: 0.46785859763622284	Train Acc: 0.7741935483870968	Valid Loss: 0.5118104914824168	Valid Acc: 0.7321428571428571
Epoch [ 34/200]	Train Loss: 0.4745188852151235	Train Acc: 0.7741935483870968	Valid Loss: 0.4827464198072751	Valid Acc: 0.75
Epoch [ 35/200]	Train Loss: 0.47009091079235077	Train Acc: 0.7688172043010753	Valid Loss: 0.4682839860518773	Valid Acc: 0.7678571428571429
Epoch [ 36/200]	Train Loss: 0.4679675449927648	Train Acc: 0.7706093189964157	Valid Loss: 0.46997373799482983	Valid Acc: 0.7678571428571429
Epoch [ 37/200]	Train Loss: 0.4646395891904831	Train Acc: 0.7688172043010753	Valid Loss: 0.45297704885403317	Valid Acc: 0.7678571428571429
Epoch [ 38/200]	Train Loss: 0.4731566508611043	Train Acc: 0.7688172043010753	Valid Loss: 0.4586116870244344	Valid Acc: 0.75
Epoch [ 39/200]	Train Loss: 0.47950418790181476	Train Acc: 0.7759856630824373	Valid Loss: 0.4556506872177124	Valid Acc: 0.7678571428571429
Epoch [ 40/200]	Train Loss: 0.47274216016133624	Train Acc: 0.7724014336917563	Valid Loss: 0.48093946774800617	Valid Acc: 0.75
Epoch [ 41/200]	Train Loss: 0.46387452880541485	Train Acc: 0.7688172043010753	Valid Loss: 0.47409480561812717	Valid Acc: 0.7678571428571429
Epoch [ 42/200]	Train Loss: 0.46822469929854077	Train Acc: 0.7688172043010753	Valid Loss: 0.4483453060189883	Valid Acc: 0.7678571428571429
Epoch [ 43/200]	Train Loss: 0.48404482503732044	Train Acc: 0.7741935483870968	Valid Loss: 0.5016530255476633	Valid Acc: 0.7321428571428571
Epoch [ 44/200]	Train Loss: 0.47006728251775104	Train Acc: 0.7759856630824373	Valid Loss: 0.45178640882174176	Valid Acc: 0.75
Epoch [ 45/200]	Train Loss: 0.4803771922985713	Train Acc: 0.7724014336917563	Valid Loss: 0.4468909328182538	Valid Acc: 0.7321428571428571
Epoch [ 46/200]	Train Loss: 0.46918147802352905	Train Acc: 0.7706093189964157	Valid Loss: 0.4593534270922343	Valid Acc: 0.7678571428571429
Epoch [ 47/200]	Train Loss: 0.481624111533165	Train Acc: 0.7670250896057348	Valid Loss: 0.46090960999329883	Valid Acc: 0.7678571428571429
Epoch [ 48/200]	Train Loss: 0.46391141414642334	Train Acc: 0.7741935483870968	Valid Loss: 0.4690512816111247	Valid Acc: 0.7678571428571429
Epoch [ 49/200]	Train Loss: 0.46993187566598255	Train Acc: 0.7652329749103942	Valid Loss: 0.47388966878255206	Valid Acc: 0.7678571428571429
Epoch [ 50/200]	Train Loss: 0.47036156555016834	Train Acc: 0.7688172043010753	Valid Loss: 0.45304909845193225	Valid Acc: 0.75
Epoch [ 51/200]	Train Loss: 0.46705969671408337	Train Acc: 0.7688172043010753	Valid Loss: 0.4508620798587799	Valid Acc: 0.75
Epoch [ 52/200]	Train Loss: 0.46788735191027325	Train Acc: 0.7759856630824373	Valid Loss: 0.46327297886212665	Valid Acc: 0.7678571428571429
Epoch [ 53/200]	Train Loss: 0.468953937292099	Train Acc: 0.7652329749103942	Valid Loss: 0.45415201038122177	Valid Acc: 0.7678571428571429
Epoch [ 54/200]	Train Loss: 0.48096299171447754	Train Acc: 0.7616487455197133	Valid Loss: 0.479374701778094	Valid Acc: 0.7678571428571429
Epoch [ 55/200]	Train Loss: 0.4703831772009532	Train Acc: 0.7688172043010753	Valid Loss: 0.4535240779320399	Valid Acc: 0.7678571428571429
Epoch [ 56/200]	Train Loss: 0.46784529586633045	Train Acc: 0.7759856630824373	Valid Loss: 0.46434619029362995	Valid Acc: 0.7321428571428571
Epoch [ 57/200]	Train Loss: 0.47749782105286914	Train Acc: 0.7741935483870968	Valid Loss: 0.464230274160703	Valid Acc: 0.7321428571428571
Epoch [ 58/200]	Train Loss: 0.4745665341615677	Train Acc: 0.7741935483870968	Valid Loss: 0.45549463232358295	Valid Acc: 0.75
Epoch [ 59/200]	Train Loss: 0.46376138428846997	Train Acc: 0.7706093189964157	Valid Loss: 0.45685569445292157	Valid Acc: 0.75
Epoch [ 60/200]	Train Loss: 0.4789963811635971	Train Acc: 0.7724014336917563	Valid Loss: 0.47766393174727756	Valid Acc: 0.7321428571428571
Epoch [ 61/200]	Train Loss: 0.46622608602046967	Train Acc: 0.7759856630824373	Valid Loss: 0.4744275485475858	Valid Acc: 0.75
Epoch [ 62/200]	Train Loss: 0.4704374819993973	Train Acc: 0.7741935483870968	Valid Loss: 0.47748662531375885	Valid Acc: 0.7678571428571429
Epoch [ 63/200]	Train Loss: 0.47135009864966076	Train Acc: 0.7670250896057348	Valid Loss: 0.4614067276318868	Valid Acc: 0.7678571428571429
Epoch [ 64/200]	Train Loss: 0.4729078362385432	Train Acc: 0.7580645161290323	Valid Loss: 0.469797320663929	Valid Acc: 0.7678571428571429
Epoch [ 65/200]	Train Loss: 0.47811468442281085	Train Acc: 0.7634408602150538	Valid Loss: 0.48125508427619934	Valid Acc: 0.7678571428571429
Epoch [ 66/200]	Train Loss: 0.4706957886616389	Train Acc: 0.7741935483870968	Valid Loss: 0.5034492313861847	Valid Acc: 0.7678571428571429
Epoch [ 67/200]	Train Loss: 0.47628086308638257	Train Acc: 0.7724014336917563	Valid Loss: 0.5123851994673411	Valid Acc: 0.7678571428571429
Epoch [ 68/200]	Train Loss: 0.47892184058825177	Train Acc: 0.7759856630824373	Valid Loss: 0.44657911360263824	Valid Acc: 0.75
Epoch [ 69/200]	Train Loss: 0.46953362226486206	Train Acc: 0.7741935483870968	Valid Loss: 0.4809803267319997	Valid Acc: 0.7678571428571429
Epoch [ 70/200]	Train Loss: 0.4692762593428294	Train Acc: 0.7688172043010753	Valid Loss: 0.4671243379513423	Valid Acc: 0.7678571428571429
Epoch [ 71/200]	Train Loss: 0.4716978619496028	Train Acc: 0.7688172043010753	Valid Loss: 0.47909169395764667	Valid Acc: 0.7678571428571429
Epoch [ 72/200]	Train Loss: 0.46679823100566864	Train Acc: 0.7759856630824373	Valid Loss: 0.4719494928916295	Valid Acc: 0.7321428571428571
Epoch [ 73/200]	Train Loss: 0.47411487499872845	Train Acc: 0.7724014336917563	Valid Loss: 0.4823636809984843	Valid Acc: 0.75
Epoch [ 74/200]	Train Loss: 0.46957512696584064	Train Acc: 0.7724014336917563	Valid Loss: 0.45804474751154584	Valid Acc: 0.7678571428571429
Epoch [ 75/200]	Train Loss: 0.4748687247435252	Train Acc: 0.7688172043010753	Valid Loss: 0.47575131555398303	Valid Acc: 0.7678571428571429
Epoch [ 76/200]	Train Loss: 0.46982377270857495	Train Acc: 0.7759856630824373	Valid Loss: 0.4528643960754077	Valid Acc: 0.75
Epoch [ 77/200]	Train Loss: 0.4719065725803375	Train Acc: 0.7777777777777778	Valid Loss: 0.4786488761504491	Valid Acc: 0.7321428571428571
Epoch [ 78/200]	Train Loss: 0.47793980439503986	Train Acc: 0.7670250896057348	Valid Loss: 0.46614330510298413	Valid Acc: 0.75
Epoch [ 79/200]	Train Loss: 0.47519826392332715	Train Acc: 0.7741935483870968	Valid Loss: 0.4819083313147227	Valid Acc: 0.7321428571428571
Epoch [ 80/200]	Train Loss: 0.4656730492909749	Train Acc: 0.7724014336917563	Valid Loss: 0.47616228957970935	Valid Acc: 0.75
Epoch [ 81/200]	Train Loss: 0.4678056786457698	Train Acc: 0.7741935483870968	Valid Loss: 0.45182109872500104	Valid Acc: 0.7678571428571429
Epoch [ 82/200]	Train Loss: 0.462322935461998	Train Acc: 0.7741935483870968	Valid Loss: 0.4540549119313558	Valid Acc: 0.7678571428571429
Epoch [ 83/200]	Train Loss: 0.4737020283937454	Train Acc: 0.7724014336917563	Valid Loss: 0.45761724809805554	Valid Acc: 0.75
Epoch [ 84/200]	Train Loss: 0.46892092128594715	Train Acc: 0.7724014336917563	Valid Loss: 0.48046382268269855	Valid Acc: 0.75
Epoch [ 85/200]	Train Loss: 0.4631789873043696	Train Acc: 0.7724014336917563	Valid Loss: 0.44739369799693424	Valid Acc: 0.75
Epoch [ 86/200]	Train Loss: 0.47397158046563465	Train Acc: 0.7724014336917563	Valid Loss: 0.4619123190641403	Valid Acc: 0.75
Epoch [ 87/200]	Train Loss: 0.46112167835235596	Train Acc: 0.7741935483870968	Valid Loss: 0.48070811728636426	Valid Acc: 0.75
Epoch [ 88/200]	Train Loss: 0.46163131296634674	Train Acc: 0.7688172043010753	Valid Loss: 0.44096387674411136	Valid Acc: 0.7678571428571429
Epoch [ 89/200]	Train Loss: 0.4733901421229045	Train Acc: 0.7724014336917563	Valid Loss: 0.4600548694531123	Valid Acc: 0.7678571428571429
Epoch [ 90/200]	Train Loss: 0.48015767335891724	Train Acc: 0.7670250896057348	Valid Loss: 0.46317411462465924	Valid Acc: 0.75
Epoch [ 91/200]	Train Loss: 0.46302586297194165	Train Acc: 0.7724014336917563	Valid Loss: 0.4753451943397522	Valid Acc: 0.75
Epoch [ 92/200]	Train Loss: 0.4813165068626404	Train Acc: 0.7724014336917563	Valid Loss: 0.4819927861293157	Valid Acc: 0.75
Epoch [ 93/200]	Train Loss: 0.4690742443005244	Train Acc: 0.7688172043010753	Valid Loss: 0.4724513093630473	Valid Acc: 0.75
Epoch [ 94/200]	Train Loss: 0.46483462552229565	Train Acc: 0.7616487455197133	Valid Loss: 0.4657393892606099	Valid Acc: 0.75
Epoch [ 95/200]	Train Loss: 0.47635993361473083	Train Acc: 0.7706093189964157	Valid Loss: 0.45493383208910626	Valid Acc: 0.7678571428571429
Epoch [ 96/200]	Train Loss: 0.46995120247205097	Train Acc: 0.7634408602150538	Valid Loss: 0.47142165899276733	Valid Acc: 0.75
Epoch [ 97/200]	Train Loss: 0.47446949779987335	Train Acc: 0.7688172043010753	Valid Loss: 0.4732543428738912	Valid Acc: 0.75
Epoch [ 98/200]	Train Loss: 0.4644021540880203	Train Acc: 0.7706093189964157	Valid Loss: 0.47887539366881055	Valid Acc: 0.75
Epoch [ 99/200]	Train Loss: 0.4713383714358012	Train Acc: 0.7724014336917563	Valid Loss: 0.46042971809705097	Valid Acc: 0.7321428571428571
Epoch [100/200]	Train Loss: 0.47323344151179	Train Acc: 0.7724014336917563	Valid Loss: 0.46668613453706104	Valid Acc: 0.7857142857142857
Epoch [101/200]	Train Loss: 0.4698674480120341	Train Acc: 0.7741935483870968	Valid Loss: 0.4582616314291954	Valid Acc: 0.7678571428571429
Epoch [102/200]	Train Loss: 0.46452052891254425	Train Acc: 0.7706093189964157	Valid Loss: 0.45542487502098083	Valid Acc: 0.7321428571428571
Epoch [103/200]	Train Loss: 0.4676894893248876	Train Acc: 0.7706093189964157	Valid Loss: 0.45564839740594226	Valid Acc: 0.75
Epoch [104/200]	Train Loss: 0.46472714841365814	Train Acc: 0.7724014336917563	Valid Loss: 0.45673465728759766	Valid Acc: 0.7678571428571429
Epoch [105/200]	Train Loss: 0.4684055795272191	Train Acc: 0.7724014336917563	Valid Loss: 0.4626997063557307	Valid Acc: 0.7857142857142857
Epoch [106/200]	Train Loss: 0.46329037348429364	Train Acc: 0.7777777777777778	Valid Loss: 0.45751819511254627	Valid Acc: 0.7678571428571429
Epoch [107/200]	Train Loss: 0.4780658533175786	Train Acc: 0.7724014336917563	Valid Loss: 0.46904919544855755	Valid Acc: 0.7321428571428571
Epoch [108/200]	Train Loss: 0.4630979895591736	Train Acc: 0.7741935483870968	Valid Loss: 0.45579005777835846	Valid Acc: 0.75
Epoch [109/200]	Train Loss: 0.47043979664643604	Train Acc: 0.7670250896057348	Valid Loss: 0.46479802827040356	Valid Acc: 0.75
Epoch [110/200]	Train Loss: 0.47251546879609424	Train Acc: 0.7670250896057348	Valid Loss: 0.46064889430999756	Valid Acc: 0.7678571428571429
Epoch [111/200]	Train Loss: 0.46995314955711365	Train Acc: 0.7724014336917563	Valid Loss: 0.4464809522032738	Valid Acc: 0.75
Epoch [112/200]	Train Loss: 0.4737424850463867	Train Acc: 0.7759856630824373	Valid Loss: 0.46877236664295197	Valid Acc: 0.75
Epoch [113/200]	Train Loss: 0.47616275151570636	Train Acc: 0.7795698924731183	Valid Loss: 0.466795672972997	Valid Acc: 0.7678571428571429
Epoch [114/200]	Train Loss: 0.4739621827999751	Train Acc: 0.7741935483870968	Valid Loss: 0.4665249412258466	Valid Acc: 0.75
Epoch [115/200]	Train Loss: 0.4719228893518448	Train Acc: 0.7724014336917563	Valid Loss: 0.46937157958745956	Valid Acc: 0.7678571428571429
Epoch [116/200]	Train Loss: 0.47441818316777545	Train Acc: 0.7777777777777778	Valid Loss: 0.45035457114378613	Valid Acc: 0.75
Epoch [117/200]	Train Loss: 0.47564472754796344	Train Acc: 0.7724014336917563	Valid Loss: 0.45759805540243786	Valid Acc: 0.75
Epoch [118/200]	Train Loss: 0.4733731398979823	Train Acc: 0.7724014336917563	Valid Loss: 0.4604708055655162	Valid Acc: 0.75
Epoch [119/200]	Train Loss: 0.47370538115501404	Train Acc: 0.7724014336917563	Valid Loss: 0.4569048335154851	Valid Acc: 0.7678571428571429
Epoch [120/200]	Train Loss: 0.4645154724518458	Train Acc: 0.7616487455197133	Valid Loss: 0.47238829731941223	Valid Acc: 0.7678571428571429
Epoch [121/200]	Train Loss: 0.46447237332661945	Train Acc: 0.7688172043010753	Valid Loss: 0.4499013076225917	Valid Acc: 0.7321428571428571
Epoch [122/200]	Train Loss: 0.4846508651971817	Train Acc: 0.7670250896057348	Valid Loss: 0.4658736338218053	Valid Acc: 0.7321428571428571
Epoch [123/200]	Train Loss: 0.47026586532592773	Train Acc: 0.7688172043010753	Valid Loss: 0.44999001423517865	Valid Acc: 0.7678571428571429
Epoch [124/200]	Train Loss: 0.47434621552626294	Train Acc: 0.7724014336917563	Valid Loss: 0.46457064151763916	Valid Acc: 0.7678571428571429
Epoch [125/200]	Train Loss: 0.47585822145144147	Train Acc: 0.7724014336917563	Valid Loss: 0.4714551617701848	Valid Acc: 0.75
Epoch [126/200]	Train Loss: 0.4748799155155818	Train Acc: 0.7688172043010753	Valid Loss: 0.45313091824452084	Valid Acc: 0.7857142857142857
Epoch [127/200]	Train Loss: 0.4712263196706772	Train Acc: 0.7759856630824373	Valid Loss: 0.4551596740881602	Valid Acc: 0.75
Epoch [128/200]	Train Loss: 0.4676681806643804	Train Acc: 0.7724014336917563	Valid Loss: 0.4745980352163315	Valid Acc: 0.75
Epoch [129/200]	Train Loss: 0.4776854068040848	Train Acc: 0.7741935483870968	Valid Loss: 0.5050150702397028	Valid Acc: 0.75
Epoch [130/200]	Train Loss: 0.46942880749702454	Train Acc: 0.7741935483870968	Valid Loss: 0.46983156601587933	Valid Acc: 0.75
Epoch [131/200]	Train Loss: 0.46586160361766815	Train Acc: 0.7741935483870968	Valid Loss: 0.4688527484734853	Valid Acc: 0.75
Epoch [132/200]	Train Loss: 0.47325370212395984	Train Acc: 0.7670250896057348	Valid Loss: 0.46353765328725177	Valid Acc: 0.7678571428571429
Epoch [133/200]	Train Loss: 0.47098669906457263	Train Acc: 0.7688172043010753	Valid Loss: 0.4557730108499527	Valid Acc: 0.7678571428571429
Epoch [134/200]	Train Loss: 0.4674142350753148	Train Acc: 0.7670250896057348	Valid Loss: 0.44808582961559296	Valid Acc: 0.75
Epoch [135/200]	Train Loss: 0.4746011843283971	Train Acc: 0.7706093189964157	Valid Loss: 0.4593231951196988	Valid Acc: 0.75
Epoch [136/200]	Train Loss: 0.47057004272937775	Train Acc: 0.7688172043010753	Valid Loss: 0.4526511530081431	Valid Acc: 0.7857142857142857
Epoch [137/200]	Train Loss: 0.4649526725212733	Train Acc: 0.7688172043010753	Valid Loss: 0.47279611229896545	Valid Acc: 0.75
Epoch [138/200]	Train Loss: 0.4633046438296636	Train Acc: 0.7706093189964157	Valid Loss: 0.484377846121788	Valid Acc: 0.75
Epoch [139/200]	Train Loss: 0.47538209954897565	Train Acc: 0.7706093189964157	Valid Loss: 0.46199579040209454	Valid Acc: 0.7678571428571429
Epoch [140/200]	Train Loss: 0.47256522874037427	Train Acc: 0.7724014336917563	Valid Loss: 0.46976951758066815	Valid Acc: 0.75
Epoch [141/200]	Train Loss: 0.4769880175590515	Train Acc: 0.7741935483870968	Valid Loss: 0.48374124864737195	Valid Acc: 0.75
Epoch [142/200]	Train Loss: 0.47469118734200794	Train Acc: 0.7777777777777778	Valid Loss: 0.4796299710869789	Valid Acc: 0.7678571428571429
Epoch [143/200]	Train Loss: 0.47034676373004913	Train Acc: 0.7724014336917563	Valid Loss: 0.478940412402153	Valid Acc: 0.7321428571428571
Epoch [144/200]	Train Loss: 0.4681936055421829	Train Acc: 0.7652329749103942	Valid Loss: 0.4721259226401647	Valid Acc: 0.7678571428571429
Epoch [145/200]	Train Loss: 0.47508302330970764	Train Acc: 0.7741935483870968	Valid Loss: 0.47863412896792096	Valid Acc: 0.7678571428571429
Epoch [146/200]	Train Loss: 0.4745720674594243	Train Acc: 0.7724014336917563	Valid Loss: 0.4597993145386378	Valid Acc: 0.7678571428571429
Epoch [147/200]	Train Loss: 0.47304482758045197	Train Acc: 0.7652329749103942	Valid Loss: 0.45163004100322723	Valid Acc: 0.75
Epoch [148/200]	Train Loss: 0.47145388027032215	Train Acc: 0.7688172043010753	Valid Loss: 0.44454358021418255	Valid Acc: 0.7678571428571429
Epoch [149/200]	Train Loss: 0.4774695932865143	Train Acc: 0.7777777777777778	Valid Loss: 0.4616009493668874	Valid Acc: 0.7678571428571429

## Test Model

In [67]:
model = torch.load('./LogisticRegressionModel.pt', weights_only=False)

with torch.no_grad():
    for X_batch, y_batch in test_loader:
        y_hat = model(X_batch)
        loss = nn.functional.l1_loss(y_hat, y_batch)
        acc = torch.sum((y_hat > 0.5).float() == y_batch).item() / len(test_set)
print(loss)
print(acc)

tensor(0.4579)
85.96103896103897